[versions]
agp = "8.6.0"
core = "1.5.0"
kotlin = "2.0.21"
junit = "4.13.2"

[libraries]
core = { module = "androidx.test:core", version.ref = "core" }
junit = { module = "junit:junit", version.ref = "junit" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
